# Generated by Django 4.1.7 on 2023-02-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchases',
            new_name='Purchase',
        ),
    ]
